// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function AIAppChat(arg1:types.AppAIChatInput):Promise<types.AppAIChatResult>;

export function AIChat(arg1:types.AIChatInput):Promise<types.AIChatResult>;

export function AIConfigActivate(arg1:types.AIActivateInput):Promise<types.AIConfigInfo>;

export function AIConfigDelete(arg1:string):Promise<types.AIConfigInfo>;

export function AIConfigGet():Promise<types.AIConfigInfo>;

export function AIConfigSave(arg1:types.AIProviderConfigInput):Promise<types.AIConfigInfo>;

export function AITest(arg1:types.AITestInput):Promise<types.AITestResult>;

export function AppsCreate(arg1:number,arg2:types.AppCreateInput):Promise<types.App>;

export function AppsDelete(arg1:number):Promise<types.Ok>;

export function AppsGet(arg1:number):Promise<types.App>;

export function AppsList(arg1:number):Promise<Array<types.App>>;

export function AppsOpenInEditor(arg1:number):Promise<types.Ok>;

export function AppsUpdate(arg1:number,arg2:types.AppUpdateInput):Promise<types.App>;

export function ConfigSetsActivate(arg1:number):Promise<types.ConfigSetActivateResult>;

export function ConfigSetsCopyFrom(arg1:number,arg2:number,arg3:types.CopyParts):Promise<types.ConfigSet>;

export function ConfigSetsCreate(arg1:number,arg2:types.ConfigSetCreateInput):Promise<types.ConfigSet>;

export function ConfigSetsDelete(arg1:number):Promise<types.Ok>;

export function ConfigSetsGetDetail(arg1:number):Promise<types.ConfigSetDetail>;

export function ConfigSetsList(arg1:number):Promise<Array<types.ConfigSet>>;

export function ConfigSetsUpdate(arg1:number,arg2:types.ConfigSetUpdateInput):Promise<types.ConfigSet>;

export function EnvVarsCreate(arg1:number,arg2:types.EnvVarCreateInput):Promise<types.EnvVar>;

export function EnvVarsDelete(arg1:number):Promise<types.Ok>;

export function EnvVarsImport(arg1:number):Promise<types.ImportEnvResult>;

export function EnvVarsList(arg1:number):Promise<Array<types.EnvVar>>;

export function EnvVarsUpdate(arg1:number,arg2:types.EnvVarUpdateInput):Promise<types.EnvVar>;

export function FsPickAppFile(arg1:number):Promise<types.PickFileResult>;

export function FsPickFile(arg1:types.FsPickFileInput):Promise<types.PickFileResult>;

export function FsPickFolder(arg1:types.FsPickFolderInput):Promise<types.PickFolderResult>;

export function FsReadAppFile(arg1:number,arg2:string):Promise<types.ReadAppFileResult>;

export function FsValidatePath(arg1:string):Promise<types.ValidatePathResult>;

export function OpenExternal(arg1:string):Promise<types.Ok>;

export function PortsKill(arg1:number):Promise<types.PortsKillResult>;

export function PortsList():Promise<types.PortsListResult>;

export function ReadyUrlPatternsCreate(arg1:types.ReadyUrlPatternCreateInput):Promise<types.ReadyUrlPattern>;

export function ReadyUrlPatternsDelete(arg1:number):Promise<types.Ok>;

export function ReadyUrlPatternsList():Promise<Array<types.ReadyUrlPattern>>;

export function ReadyUrlPatternsUpdate(arg1:number,arg2:types.ReadyUrlPatternUpdateInput):Promise<types.ReadyUrlPattern>;

export function RunConfigGet(arg1:number):Promise<types.RunConfig>;

export function RunConfigSave(arg1:number,arg2:types.RunConfigSaveInput):Promise<types.RunConfig>;

export function RunnerLogs(arg1:number):Promise<types.RunnerLogsSnapshot>;

export function RunnerReload(arg1:number):Promise<types.StatusEvent>;

export function RunnerRun(arg1:number):Promise<types.StatusEvent>;

export function RunnerStatus(arg1:number):Promise<types.StatusEvent>;

export function RunnerStop(arg1:number):Promise<types.StatusEvent>;

export function RunnerWorkspaceStatus(arg1:number):Promise<Array<types.StatusEvent>>;

export function SettingsGet():Promise<Record<string, string>>;

export function SettingsSet(arg1:string,arg2:string):Promise<Record<string, string>>;

export function TemplatesCreate(arg1:number,arg2:types.TemplateCreateInput):Promise<types.Template>;

export function TemplatesDelete(arg1:number):Promise<types.Ok>;

export function TemplatesList(arg1:number):Promise<Array<types.Template>>;

export function TemplatesUpdate(arg1:number,arg2:types.TemplateUpdateInput):Promise<types.Template>;

export function WorkspacesCreate(arg1:types.WorkspaceCreateInput):Promise<types.Workspace>;

export function WorkspacesDelete(arg1:number):Promise<types.Ok>;

export function WorkspacesList():Promise<Array<types.Workspace>>;

export function WorkspacesUpdate(arg1:number,arg2:types.WorkspaceUpdateInput):Promise<types.Workspace>;
