// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAppChat(arg1) {
  return window['go']['main']['App']['AIAppChat'](arg1);
}

export function AIChat(arg1) {
  return window['go']['main']['App']['AIChat'](arg1);
}

export function AIConfigActivate(arg1) {
  return window['go']['main']['App']['AIConfigActivate'](arg1);
}

export function AIConfigDelete(arg1) {
  return window['go']['main']['App']['AIConfigDelete'](arg1);
}

export function AIConfigGet() {
  return window['go']['main']['App']['AIConfigGet']();
}

export function AIConfigSave(arg1) {
  return window['go']['main']['App']['AIConfigSave'](arg1);
}

export function AITest(arg1) {
  return window['go']['main']['App']['AITest'](arg1);
}

export function AppsCreate(arg1, arg2) {
  return window['go']['main']['App']['AppsCreate'](arg1, arg2);
}

export function AppsDelete(arg1) {
  return window['go']['main']['App']['AppsDelete'](arg1);
}

export function AppsGet(arg1) {
  return window['go']['main']['App']['AppsGet'](arg1);
}

export function AppsList(arg1) {
  return window['go']['main']['App']['AppsList'](arg1);
}

export function AppsOpenInEditor(arg1) {
  return window['go']['main']['App']['AppsOpenInEditor'](arg1);
}

export function AppsUpdate(arg1, arg2) {
  return window['go']['main']['App']['AppsUpdate'](arg1, arg2);
}

export function ConfigSetsActivate(arg1) {
  return window['go']['main']['App']['ConfigSetsActivate'](arg1);
}

export function ConfigSetsCopyFrom(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfigSetsCopyFrom'](arg1, arg2, arg3);
}

export function ConfigSetsCreate(arg1, arg2) {
  return window['go']['main']['App']['ConfigSetsCreate'](arg1, arg2);
}

export function ConfigSetsDelete(arg1) {
  return window['go']['main']['App']['ConfigSetsDelete'](arg1);
}

export function ConfigSetsGetDetail(arg1) {
  return window['go']['main']['App']['ConfigSetsGetDetail'](arg1);
}

export function ConfigSetsList(arg1) {
  return window['go']['main']['App']['ConfigSetsList'](arg1);
}

export function ConfigSetsUpdate(arg1, arg2) {
  return window['go']['main']['App']['ConfigSetsUpdate'](arg1, arg2);
}

export function EnvVarsCreate(arg1, arg2) {
  return window['go']['main']['App']['EnvVarsCreate'](arg1, arg2);
}

export function EnvVarsDelete(arg1) {
  return window['go']['main']['App']['EnvVarsDelete'](arg1);
}

export function EnvVarsImport(arg1) {
  return window['go']['main']['App']['EnvVarsImport'](arg1);
}

export function EnvVarsList(arg1) {
  return window['go']['main']['App']['EnvVarsList'](arg1);
}

export function EnvVarsUpdate(arg1, arg2) {
  return window['go']['main']['App']['EnvVarsUpdate'](arg1, arg2);
}

export function FsPickAppFile(arg1) {
  return window['go']['main']['App']['FsPickAppFile'](arg1);
}

export function FsPickFile(arg1) {
  return window['go']['main']['App']['FsPickFile'](arg1);
}

export function FsPickFolder(arg1) {
  return window['go']['main']['App']['FsPickFolder'](arg1);
}

export function FsReadAppFile(arg1, arg2) {
  return window['go']['main']['App']['FsReadAppFile'](arg1, arg2);
}

export function FsValidatePath(arg1) {
  return window['go']['main']['App']['FsValidatePath'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function PortsKill(arg1) {
  return window['go']['main']['App']['PortsKill'](arg1);
}

export function PortsList() {
  return window['go']['main']['App']['PortsList']();
}

export function ReadyUrlPatternsCreate(arg1) {
  return window['go']['main']['App']['ReadyUrlPatternsCreate'](arg1);
}

export function ReadyUrlPatternsDelete(arg1) {
  return window['go']['main']['App']['ReadyUrlPatternsDelete'](arg1);
}

export function ReadyUrlPatternsList() {
  return window['go']['main']['App']['ReadyUrlPatternsList']();
}

export function ReadyUrlPatternsUpdate(arg1, arg2) {
  return window['go']['main']['App']['ReadyUrlPatternsUpdate'](arg1, arg2);
}

export function RunConfigGet(arg1) {
  return window['go']['main']['App']['RunConfigGet'](arg1);
}

export function RunConfigSave(arg1, arg2) {
  return window['go']['main']['App']['RunConfigSave'](arg1, arg2);
}

export function RunnerLogs(arg1) {
  return window['go']['main']['App']['RunnerLogs'](arg1);
}

export function RunnerReload(arg1) {
  return window['go']['main']['App']['RunnerReload'](arg1);
}

export function RunnerRun(arg1) {
  return window['go']['main']['App']['RunnerRun'](arg1);
}

export function RunnerStatus(arg1) {
  return window['go']['main']['App']['RunnerStatus'](arg1);
}

export function RunnerStop(arg1) {
  return window['go']['main']['App']['RunnerStop'](arg1);
}

export function RunnerWorkspaceStatus(arg1) {
  return window['go']['main']['App']['RunnerWorkspaceStatus'](arg1);
}

export function SettingsGet() {
  return window['go']['main']['App']['SettingsGet']();
}

export function SettingsSet(arg1, arg2) {
  return window['go']['main']['App']['SettingsSet'](arg1, arg2);
}

export function TemplatesCreate(arg1, arg2) {
  return window['go']['main']['App']['TemplatesCreate'](arg1, arg2);
}

export function TemplatesDelete(arg1) {
  return window['go']['main']['App']['TemplatesDelete'](arg1);
}

export function TemplatesList(arg1) {
  return window['go']['main']['App']['TemplatesList'](arg1);
}

export function TemplatesUpdate(arg1, arg2) {
  return window['go']['main']['App']['TemplatesUpdate'](arg1, arg2);
}

export function WorkspacesCreate(arg1) {
  return window['go']['main']['App']['WorkspacesCreate'](arg1);
}

export function WorkspacesDelete(arg1) {
  return window['go']['main']['App']['WorkspacesDelete'](arg1);
}

export function WorkspacesList() {
  return window['go']['main']['App']['WorkspacesList']();
}

export function WorkspacesUpdate(arg1, arg2) {
  return window['go']['main']['App']['WorkspacesUpdate'](arg1, arg2);
}
