// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type App struct {
	ID                int64  `json:"id"`
	WorkspaceID       int64  `json:"workspace_id"`
	Name              string `json:"name"`
	ProjectPath       string `json:"project_path"`
	ActiveConfigSetID *int64 `json:"active_config_set_id"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type AppSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type ConfigSet struct {
	ID        int64  `json:"id"`
	AppID     int64  `json:"app_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type EnvVar struct {
	ID          int64  `json:"id"`
	ConfigSetID int64  `json:"config_set_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type ReadyUrlPattern struct {
	ID        int64   `json:"id"`
	Key       *string `json:"key"`
	Label     string  `json:"label"`
	Pattern   string  `json:"pattern"`
	Flags     string  `json:"flags"`
	SortOrder int64   `json:"sort_order"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

type RunCommand struct {
	ID          int64   `json:"id"`
	RunConfigID int64   `json:"run_config_id"`
	Label       *string `json:"label"`
	Command     string  `json:"command"`
	SortOrder   int64   `json:"sort_order"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type RunConfig struct {
	ID          int64  `json:"id"`
	ConfigSetID int64  `json:"config_set_id"`
	Mode        string `json:"mode"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Template struct {
	ID          int64  `json:"id"`
	ConfigSetID int64  `json:"config_set_id"`
	FilePath    string `json:"file_path"`
	Content     string `json:"content"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Workspace struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Icon      *string `json:"icon"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}
