// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (workspace_id, name, project_path)
VALUES (?, ?, ?)
RETURNING id, workspace_id, name, project_path, active_config_set_id, created_at, updated_at
`

type CreateAppParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
	ProjectPath string `json:"project_path"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, createApp, arg.WorkspaceID, arg.Name, arg.ProjectPath)
	var i App
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ProjectPath,
		&i.ActiveConfigSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConfigSet = `-- name: CreateConfigSet :one
INSERT INTO config_sets (app_id, name) VALUES (?, ?) RETURNING id, app_id, name, created_at, updated_at
`

type CreateConfigSetParams struct {
	AppID int64  `json:"app_id"`
	Name  string `json:"name"`
}

func (q *Queries) CreateConfigSet(ctx context.Context, arg CreateConfigSetParams) (ConfigSet, error) {
	row := q.db.QueryRowContext(ctx, createConfigSet, arg.AppID, arg.Name)
	var i ConfigSet
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEnvVar = `-- name: CreateEnvVar :one
INSERT INTO env_vars (config_set_id, key, value, include_in_ai) VALUES (?, ?, ?, ?) RETURNING id, config_set_id, "key", value, include_in_ai, created_at, updated_at
`

type CreateEnvVarParams struct {
	ConfigSetID int64  `json:"config_set_id"`
	Key         string `json:"key"`
	Value       string `json:"value"`
	IncludeInAi int64  `json:"include_in_ai"`
}

func (q *Queries) CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, createEnvVar,
		arg.ConfigSetID,
		arg.Key,
		arg.Value,
		arg.IncludeInAi,
	)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Key,
		&i.Value,
		&i.IncludeInAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReadyUrlPattern = `-- name: CreateReadyUrlPattern :one
INSERT INTO ready_url_patterns (key, label, pattern, flags, sort_order)
VALUES (?, ?, ?, ?, ?)
RETURNING id, "key", label, pattern, flags, sort_order, created_at, updated_at
`

type CreateReadyUrlPatternParams struct {
	Key       *string `json:"key"`
	Label     string  `json:"label"`
	Pattern   string  `json:"pattern"`
	Flags     string  `json:"flags"`
	SortOrder int64   `json:"sort_order"`
}

func (q *Queries) CreateReadyUrlPattern(ctx context.Context, arg CreateReadyUrlPatternParams) (ReadyUrlPattern, error) {
	row := q.db.QueryRowContext(ctx, createReadyUrlPattern,
		arg.Key,
		arg.Label,
		arg.Pattern,
		arg.Flags,
		arg.SortOrder,
	)
	var i ReadyUrlPattern
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Pattern,
		&i.Flags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunCommand = `-- name: CreateRunCommand :one
INSERT INTO run_commands (run_config_id, label, command, sort_order)
VALUES (?, ?, ?, ?)
RETURNING id, run_config_id, label, command, sort_order, created_at, updated_at
`

type CreateRunCommandParams struct {
	RunConfigID int64   `json:"run_config_id"`
	Label       *string `json:"label"`
	Command     string  `json:"command"`
	SortOrder   int64   `json:"sort_order"`
}

func (q *Queries) CreateRunCommand(ctx context.Context, arg CreateRunCommandParams) (RunCommand, error) {
	row := q.db.QueryRowContext(ctx, createRunCommand,
		arg.RunConfigID,
		arg.Label,
		arg.Command,
		arg.SortOrder,
	)
	var i RunCommand
	err := row.Scan(
		&i.ID,
		&i.RunConfigID,
		&i.Label,
		&i.Command,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunConfig = `-- name: CreateRunConfig :one
INSERT INTO run_configs (config_set_id, mode) VALUES (?, ?) RETURNING id, config_set_id, mode, created_at, updated_at
`

type CreateRunConfigParams struct {
	ConfigSetID int64  `json:"config_set_id"`
	Mode        string `json:"mode"`
}

func (q *Queries) CreateRunConfig(ctx context.Context, arg CreateRunConfigParams) (RunConfig, error) {
	row := q.db.QueryRowContext(ctx, createRunConfig, arg.ConfigSetID, arg.Mode)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (config_set_id, file_path, content) VALUES (?, ?, ?) RETURNING id, config_set_id, file_path, content, created_at, updated_at
`

type CreateTemplateParams struct {
	ConfigSetID int64  `json:"config_set_id"`
	FilePath    string `json:"file_path"`
	Content     string `json:"content"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, createTemplate, arg.ConfigSetID, arg.FilePath, arg.Content)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.FilePath,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, icon) VALUES (?, ?) RETURNING id, name, icon, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name string  `json:"name"`
	Icon *string `json:"icon"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, arg.Name, arg.Icon)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApp = `-- name: DeleteApp :execrows
DELETE FROM apps WHERE id = ?
`

func (q *Queries) DeleteApp(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteApp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteConfigSet = `-- name: DeleteConfigSet :execrows
DELETE FROM config_sets WHERE id = ?
`

func (q *Queries) DeleteConfigSet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConfigSet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEnvVar = `-- name: DeleteEnvVar :execrows
DELETE FROM env_vars WHERE id = ?
`

func (q *Queries) DeleteEnvVar(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEnvVar, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEnvVarsByConfigSet = `-- name: DeleteEnvVarsByConfigSet :exec
DELETE FROM env_vars WHERE config_set_id = ?
`

func (q *Queries) DeleteEnvVarsByConfigSet(ctx context.Context, configSetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvVarsByConfigSet, configSetID)
	return err
}

const deleteReadyUrlPattern = `-- name: DeleteReadyUrlPattern :execrows
DELETE FROM ready_url_patterns WHERE id = ?
`

func (q *Queries) DeleteReadyUrlPattern(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReadyUrlPattern, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunCommands = `-- name: DeleteRunCommands :exec
DELETE FROM run_commands WHERE run_config_id = ?
`

func (q *Queries) DeleteRunCommands(ctx context.Context, runConfigID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRunCommands, runConfigID)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM app_settings WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM templates WHERE id = ?
`

func (q *Queries) DeleteTemplate(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTemplatesByConfigSet = `-- name: DeleteTemplatesByConfigSet :exec
DELETE FROM templates WHERE config_set_id = ?
`

func (q *Queries) DeleteTemplatesByConfigSet(ctx context.Context, configSetID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTemplatesByConfigSet, configSetID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getApp = `-- name: GetApp :one
SELECT
  a.id, a.workspace_id, a.name, a.project_path, a.active_config_set_id,
  a.created_at, a.updated_at,
  cs.name AS active_config_set_name
FROM apps a
LEFT JOIN config_sets cs ON cs.id = a.active_config_set_id
WHERE a.id = ?
`

type GetAppRow struct {
	ID                  int64   `json:"id"`
	WorkspaceID         int64   `json:"workspace_id"`
	Name                string  `json:"name"`
	ProjectPath         string  `json:"project_path"`
	ActiveConfigSetID   *int64  `json:"active_config_set_id"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	ActiveConfigSetName *string `json:"active_config_set_name"`
}

func (q *Queries) GetApp(ctx context.Context, id int64) (GetAppRow, error) {
	row := q.db.QueryRowContext(ctx, getApp, id)
	var i GetAppRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ProjectPath,
		&i.ActiveConfigSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveConfigSetName,
	)
	return i, err
}

const getConfigSet = `-- name: GetConfigSet :one
SELECT id, app_id, name, created_at, updated_at FROM config_sets WHERE id = ?
`

func (q *Queries) GetConfigSet(ctx context.Context, id int64) (ConfigSet, error) {
	row := q.db.QueryRowContext(ctx, getConfigSet, id)
	var i ConfigSet
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVar = `-- name: GetEnvVar :one
SELECT id, config_set_id, "key", value, include_in_ai, created_at, updated_at FROM env_vars WHERE id = ?
`

func (q *Queries) GetEnvVar(ctx context.Context, id int64) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, getEnvVar, id)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Key,
		&i.Value,
		&i.IncludeInAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVarByKey = `-- name: GetEnvVarByKey :one
SELECT id, config_set_id, "key", value, include_in_ai, created_at, updated_at FROM env_vars WHERE config_set_id = ? AND key = ?
`

type GetEnvVarByKeyParams struct {
	ConfigSetID int64  `json:"config_set_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetEnvVarByKey(ctx context.Context, arg GetEnvVarByKeyParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, getEnvVarByKey, arg.ConfigSetID, arg.Key)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Key,
		&i.Value,
		&i.IncludeInAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReadyUrlPattern = `-- name: GetReadyUrlPattern :one
SELECT id, "key", label, pattern, flags, sort_order, created_at, updated_at FROM ready_url_patterns WHERE id = ?
`

func (q *Queries) GetReadyUrlPattern(ctx context.Context, id int64) (ReadyUrlPattern, error) {
	row := q.db.QueryRowContext(ctx, getReadyUrlPattern, id)
	var i ReadyUrlPattern
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Pattern,
		&i.Flags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunConfigByConfigSet = `-- name: GetRunConfigByConfigSet :one
SELECT id, config_set_id, mode, created_at, updated_at FROM run_configs WHERE config_set_id = ?
`

// run_configs (db/run-configs.ts)
func (q *Queries) GetRunConfigByConfigSet(ctx context.Context, configSetID int64) (RunConfig, error) {
	row := q.db.QueryRowContext(ctx, getRunConfigByConfigSet, configSetID)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at FROM app_settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, config_set_id, file_path, content, created_at, updated_at FROM templates WHERE id = ?
`

func (q *Queries) GetTemplate(ctx context.Context, id int64) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.FilePath,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateByPath = `-- name: GetTemplateByPath :one
SELECT id, config_set_id, file_path, content, created_at, updated_at FROM templates WHERE config_set_id = ? AND file_path = ?
`

type GetTemplateByPathParams struct {
	ConfigSetID int64  `json:"config_set_id"`
	FilePath    string `json:"file_path"`
}

func (q *Queries) GetTemplateByPath(ctx context.Context, arg GetTemplateByPathParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplateByPath, arg.ConfigSetID, arg.FilePath)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.FilePath,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, icon, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppsByWorkspace = `-- name: ListAppsByWorkspace :many
SELECT
  a.id, a.workspace_id, a.name, a.project_path, a.active_config_set_id,
  a.created_at, a.updated_at,
  cs.name AS active_config_set_name
FROM apps a
LEFT JOIN config_sets cs ON cs.id = a.active_config_set_id
WHERE a.workspace_id = ?
ORDER BY a.name COLLATE NOCASE ASC
`

type ListAppsByWorkspaceRow struct {
	ID                  int64   `json:"id"`
	WorkspaceID         int64   `json:"workspace_id"`
	Name                string  `json:"name"`
	ProjectPath         string  `json:"project_path"`
	ActiveConfigSetID   *int64  `json:"active_config_set_id"`
	CreatedAt           string  `json:"created_at"`
	UpdatedAt           string  `json:"updated_at"`
	ActiveConfigSetName *string `json:"active_config_set_name"`
}

// apps (db/apps.ts)
func (q *Queries) ListAppsByWorkspace(ctx context.Context, workspaceID int64) ([]ListAppsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listAppsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppsByWorkspaceRow{}
	for rows.Next() {
		var i ListAppsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ProjectPath,
			&i.ActiveConfigSetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveConfigSetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigSetsByApp = `-- name: ListConfigSetsByApp :many
SELECT id, app_id, name, created_at, updated_at FROM config_sets WHERE app_id = ? ORDER BY name COLLATE NOCASE ASC
`

// config_sets (db/config-sets.ts)
func (q *Queries) ListConfigSetsByApp(ctx context.Context, appID int64) ([]ConfigSet, error) {
	rows, err := q.db.QueryContext(ctx, listConfigSetsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigSet{}
	for rows.Next() {
		var i ConfigSet
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarsByConfigSet = `-- name: ListEnvVarsByConfigSet :many
SELECT id, config_set_id, "key", value, include_in_ai, created_at, updated_at FROM env_vars WHERE config_set_id = ? ORDER BY key COLLATE NOCASE ASC
`

// env_vars (db/env-vars.ts)
func (q *Queries) ListEnvVarsByConfigSet(ctx context.Context, configSetID int64) ([]EnvVar, error) {
	rows, err := q.db.QueryContext(ctx, listEnvVarsByConfigSet, configSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvVar{}
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ConfigSetID,
			&i.Key,
			&i.Value,
			&i.IncludeInAi,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyUrlPatterns = `-- name: ListReadyUrlPatterns :many
SELECT id, "key", label, pattern, flags, sort_order, created_at, updated_at FROM ready_url_patterns ORDER BY sort_order ASC, id ASC
`

// ready_url_patterns (db/ready-url-patterns.ts)
func (q *Queries) ListReadyUrlPatterns(ctx context.Context) ([]ReadyUrlPattern, error) {
	rows, err := q.db.QueryContext(ctx, listReadyUrlPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadyUrlPattern{}
	for rows.Next() {
		var i ReadyUrlPattern
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Label,
			&i.Pattern,
			&i.Flags,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCommands = `-- name: ListRunCommands :many
SELECT id, run_config_id, label, command, sort_order, created_at, updated_at FROM run_commands
WHERE run_config_id = ?
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListRunCommands(ctx context.Context, runConfigID int64) ([]RunCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunCommands, runConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunCommand{}
	for rows.Next() {
		var i RunCommand
		if err := rows.Scan(
			&i.ID,
			&i.RunConfigID,
			&i.Label,
			&i.Command,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, updated_at FROM app_settings
`

// settings (db/settings.ts)
func (q *Queries) ListSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByConfigSet = `-- name: ListTemplatesByConfigSet :many
SELECT id, config_set_id, file_path, content, created_at, updated_at FROM templates WHERE config_set_id = ? ORDER BY file_path COLLATE NOCASE ASC
`

// templates (db/templates.ts)
func (q *Queries) ListTemplatesByConfigSet(ctx context.Context, configSetID int64) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplatesByConfigSet, configSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.ConfigSetID,
			&i.FilePath,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, icon, created_at, updated_at FROM workspaces ORDER BY name COLLATE NOCASE ASC
`

// workspaces (db/workspaces.ts)
func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxReadyUrlSortOrder = `-- name: MaxReadyUrlSortOrder :one
SELECT COALESCE(max(sort_order), -1) AS max_order FROM ready_url_patterns
`

func (q *Queries) MaxReadyUrlSortOrder(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxReadyUrlSortOrder)
	var max_order interface{}
	err := row.Scan(&max_order)
	return max_order, err
}

const setActiveConfigSet = `-- name: SetActiveConfigSet :one
UPDATE apps
SET active_config_set_id = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, name, project_path, active_config_set_id, created_at, updated_at
`

type SetActiveConfigSetParams struct {
	ActiveConfigSetID *int64 `json:"active_config_set_id"`
	ID                int64  `json:"id"`
}

func (q *Queries) SetActiveConfigSet(ctx context.Context, arg SetActiveConfigSetParams) (App, error) {
	row := q.db.QueryRowContext(ctx, setActiveConfigSet, arg.ActiveConfigSetID, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ProjectPath,
		&i.ActiveConfigSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchRunConfig = `-- name: TouchRunConfig :one
UPDATE run_configs
SET updated_at = datetime('now')
WHERE id = ?
RETURNING id, config_set_id, mode, created_at, updated_at
`

func (q *Queries) TouchRunConfig(ctx context.Context, id int64) (RunConfig, error) {
	row := q.db.QueryRowContext(ctx, touchRunConfig, id)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps
SET name = ?, project_path = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, workspace_id, name, project_path, active_config_set_id, created_at, updated_at
`

type UpdateAppParams struct {
	Name        string `json:"name"`
	ProjectPath string `json:"project_path"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRowContext(ctx, updateApp, arg.Name, arg.ProjectPath, arg.ID)
	var i App
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ProjectPath,
		&i.ActiveConfigSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConfigSet = `-- name: UpdateConfigSet :one
UPDATE config_sets
SET name = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, app_id, name, created_at, updated_at
`

type UpdateConfigSetParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateConfigSet(ctx context.Context, arg UpdateConfigSetParams) (ConfigSet, error) {
	row := q.db.QueryRowContext(ctx, updateConfigSet, arg.Name, arg.ID)
	var i ConfigSet
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvVar = `-- name: UpdateEnvVar :one
UPDATE env_vars
SET key = ?, value = ?, include_in_ai = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, config_set_id, "key", value, include_in_ai, created_at, updated_at
`

type UpdateEnvVarParams struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IncludeInAi int64  `json:"include_in_ai"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRowContext(ctx, updateEnvVar,
		arg.Key,
		arg.Value,
		arg.IncludeInAi,
		arg.ID,
	)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Key,
		&i.Value,
		&i.IncludeInAi,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReadyUrlPattern = `-- name: UpdateReadyUrlPattern :one
UPDATE ready_url_patterns
SET label = ?, pattern = ?, flags = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, "key", label, pattern, flags, sort_order, created_at, updated_at
`

type UpdateReadyUrlPatternParams struct {
	Label   string `json:"label"`
	Pattern string `json:"pattern"`
	Flags   string `json:"flags"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateReadyUrlPattern(ctx context.Context, arg UpdateReadyUrlPatternParams) (ReadyUrlPattern, error) {
	row := q.db.QueryRowContext(ctx, updateReadyUrlPattern,
		arg.Label,
		arg.Pattern,
		arg.Flags,
		arg.ID,
	)
	var i ReadyUrlPattern
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Label,
		&i.Pattern,
		&i.Flags,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReadyUrlPatternSeed = `-- name: UpdateReadyUrlPatternSeed :exec
UPDATE ready_url_patterns
SET key = ?, label = ?, flags = ?, sort_order = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateReadyUrlPatternSeedParams struct {
	Key       *string `json:"key"`
	Label     string  `json:"label"`
	Flags     string  `json:"flags"`
	SortOrder int64   `json:"sort_order"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateReadyUrlPatternSeed(ctx context.Context, arg UpdateReadyUrlPatternSeedParams) error {
	_, err := q.db.ExecContext(ctx, updateReadyUrlPatternSeed,
		arg.Key,
		arg.Label,
		arg.Flags,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const updateRunConfigMode = `-- name: UpdateRunConfigMode :one
UPDATE run_configs
SET mode = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, config_set_id, mode, created_at, updated_at
`

type UpdateRunConfigModeParams struct {
	Mode string `json:"mode"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateRunConfigMode(ctx context.Context, arg UpdateRunConfigModeParams) (RunConfig, error) {
	row := q.db.QueryRowContext(ctx, updateRunConfigMode, arg.Mode, arg.ID)
	var i RunConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET file_path = ?, content = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, config_set_id, file_path, content, created_at, updated_at
`

type UpdateTemplateParams struct {
	FilePath string `json:"file_path"`
	Content  string `json:"content"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRowContext(ctx, updateTemplate, arg.FilePath, arg.Content, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.ConfigSetID,
		&i.FilePath,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = ?, icon = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, name, icon, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	Name string  `json:"name"`
	Icon *string `json:"icon"`
	ID   int64   `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace, arg.Name, arg.Icon, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value)
VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = datetime('now')
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
