/**
 * compile.ts — production single-binary build.
 *
 * Entry: `bun run compile` | `compile:win` | `compile:mac` | `compile:linux`
 *
 * 1. Builds the Vite frontend → `dist/`
 * 2. Generates embeds for `dist/` + shared `drizzle/`
 * 3. Compiles `server/index.ts` into `release/workspace-manager*` (cross-compile via Bun `--target`)
 * 4. Restores the empty embeds stubs so day-to-day `bun` runs keep using disk paths
 */
import { readdirSync, writeFileSync } from "node:fs"
import { join, relative } from "node:path"

const ROOT = join(import.meta.dir, "..")
const REPO_ROOT = join(ROOT, "..")
const STATIC_EMBEDS_PATH = join(ROOT, "server", "embedded-assets.ts")
const MIGRATION_EMBEDS_PATH = join(REPO_ROOT, "db", "embedded-migrations.ts")

const PLATFORMS = {
  win: { target: "bun-windows-x64", outfile: "workspace-manager-windows" },
  mac: { target: "bun-darwin-arm64", outfile: "workspace-manager-macos" },
  linux: { target: "bun-linux-x64", outfile: "workspace-manager-linux" },
} as const

type Platform = keyof typeof PLATFORMS

const arg = process.argv[2]
if (arg && !(arg in PLATFORMS)) {
  console.error(`Unknown platform "${arg}". Use win, mac, or linux.`)
  process.exit(1)
}

const platform = arg as Platform | undefined
const spec = platform ? PLATFORMS[platform] : undefined
const OUTFILE = join(ROOT, "release", spec?.outfile ?? "workspace-manager")

const STATIC_STUB = `/**
 * Populated by \`bun run compile\` with \`with { type: "file" }\` imports so the
 * frontend ships inside the standalone binary.
 * Empty in normal \`bun\` / \`vite\` workflows — those read from disk instead.
 */
export const staticFiles: Record<string, string> = {}
`

const MIGRATION_STUB = `/**
 * Populated by \`bun run compile\` with \`with { type: "file" }\` imports so
 * drizzle migrations ship inside the bun_backend standalone binary.
 * Empty in normal \`bun\` / \`vite\` workflows — those read from disk instead.
 */
export const migrationFiles: Record<string, string> = {}
`

function walkFiles(dir: string): string[] {
  const out: string[] = []
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, ent.name)
    if (ent.isDirectory()) out.push(...walkFiles(full))
    else out.push(full)
  }
  return out
}

function toPosix(path: string) {
  return path.replaceAll("\\", "/")
}

function genEmbeds() {
  const distDir = join(ROOT, "dist")
  const drizzleDir = join(REPO_ROOT, "drizzle")
  const dbDir = join(REPO_ROOT, "db")

  const staticPaths = walkFiles(distDir)
  const migrationPaths = walkFiles(drizzleDir)

  const staticLines: string[] = [
    "// Generated by scripts/compile.ts — do not edit",
    "",
  ]
  const staticEntries: string[] = []
  staticPaths.forEach((abs, i) => {
    const relFromServer = toPosix(relative(join(ROOT, "server"), abs))
    const key = toPosix(relative(distDir, abs))
    staticLines.push(`import s${i} from "${relFromServer}" with { type: "file" }`)
    staticEntries.push(`  ${JSON.stringify(key)}: s${i},`)
  })
  staticLines.push(
    "",
    "export const staticFiles: Record<string, string> = {",
    ...staticEntries,
    "}",
    ""
  )

  const migrationLines: string[] = [
    "// Generated by scripts/compile.ts — do not edit",
    "",
  ]
  const migrationEntries: string[] = []
  migrationPaths.forEach((abs, i) => {
    const relFromDb = toPosix(relative(dbDir, abs))
    const key = toPosix(relative(drizzleDir, abs))
    migrationLines.push(`import m${i} from "${relFromDb}" with { type: "file" }`)
    migrationEntries.push(`  ${JSON.stringify(key)}: m${i},`)
  })
  migrationLines.push(
    "",
    "export const migrationFiles: Record<string, string> = {",
    ...migrationEntries,
    "}",
    ""
  )

  writeFileSync(STATIC_EMBEDS_PATH, staticLines.join("\n"))
  writeFileSync(MIGRATION_EMBEDS_PATH, migrationLines.join("\n"))
  console.log(
    `Embedded ${staticPaths.length} frontend files + ${migrationPaths.length} migration files`
  )
}

console.log("Building frontend…")
const build = Bun.spawn(["bun", "run", "bun_backend:build"], {
  cwd: REPO_ROOT,
  stdout: "inherit",
  stderr: "inherit",
  stdin: "inherit",
})
const buildCode = await build.exited
if (buildCode !== 0) {
  console.error("Frontend build failed")
  process.exit(buildCode)
}

try {
  genEmbeds()

  console.log(
    spec
      ? `Compiling standalone binary for ${platform} (${spec.target}) → ${OUTFILE}`
      : `Compiling standalone binary for this machine → ${OUTFILE}`
  )
  const result = await Bun.build({
    entrypoints: [join(ROOT, "server", "index.ts")],
    compile: {
      outfile: OUTFILE,
      ...(spec ? { target: spec.target } : {}),
    },
  })

  if (!result.success) {
    console.error("Compile failed:")
    for (const log of result.logs) console.error(log)
    process.exit(1)
  }

  const built = result.outputs[0]?.path ?? OUTFILE
  console.log(`Done: ${built}`)
} finally {
  writeFileSync(STATIC_EMBEDS_PATH, STATIC_STUB)
  writeFileSync(MIGRATION_EMBEDS_PATH, MIGRATION_STUB)
}
